version: '3.9'  # Use the desired Docker Compose version

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=socialmediaapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  social_media_api:
    image: social_media_api  # Use the image name from step 2 if you have a Dockerfile
    container_name: social_media_api
    restart: unless-stopped
    ports:
      - 8011:8011  # Map the container's port 8080 to the host's port 8080 (change if needed)
    environment:
      # Add any environment variables needed for your Spring Boot application
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/socialmediaapi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - postgres  # Make sure the 'postgres' service is started before starting your app container

volumes:
  postgres_data:
