
jwt:
  expiration:
    access-token: 86400000
    refresh-token: 259200000

spring:
  datasource:
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socialmediaapi
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
server:
  port: 8010